---
title: "The One Thing: Notes"
date: 2018-05-23T08:16:49+02:00
draft: false
---

* The Lies


** Self-Discipline

You only need just enough discipline until you've formed a habit. That means success is actually a short race.

1. Choose the right habit.
2. Use just enough discipline to establish it.


** Balance
The magic happens at the extremes. Time waits for no one. In the middle, not much happens.

Extraordinary results require extremely focused attention but you have multiple, competing priorities. Enter *counterbalancing*:

1. Leave things undone
2. Have extreme focus and get extraordinary results
3. Swing back to the other side and repeat

In work, you can swing extremely far. In your personal life, you'll need to be less extreme because you can't afford things to get that much out of hand.

Stop thinking of /balance/ but call it /priority/---that'll help you get a good feel of how to manage this.


** Big is Bad

No one knows our limits. If you knew, you'd probably get as close as you could to it.

The only actions that lead to succeeding big are thos that started from thinking big in the first place.

As you experience big, you /become/ big.

Don't fear thinking big. Fear mediocricy. Fear waste. Fear the lack of living to your fullest.
